basket = [['apple','bananas'],['milk','water']]
# print(basket)
# input('Press enter to change the content............')
# print('Here is the updated basket ')
# basket [0].insert(0, 'Oranges')
# basket [0].insert(-1, 'Kiwis')
# basket [1].insert(0, 'Coffee')
# basket [1].append('Tea')
# basket [1].remove('water')
# basket.append([1,2,3])
# print(basket)